name: Hello world github actions

on: 
 workflow_dispatch: 
 push:
   branches:
     - main

jobs:
  first: 
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v6.0.2

     - name: Checkout other repo
       uses: actions/checkout@v6.0.2
       with:
         repository: mikhailtchesnokov/NodeJsLabs
         path: ./node-js-labs

     - name: Show runner info
       run: |
         uname -a 
         pwd
         ls -la
         
  second:
   runs-on: ubuntu-latest
   env:
     CUSTOM_HOSTNAME: "custom_host"
   steps:
     - name: Printing custom host name
       run: |
        echo "Custom host name: $CUSTOM_HOSTNAME"
     - name: Printing custom host name again
       env:
         CUSTOM_HOSTNAME: "custom_host2"
       run: |
        echo "Custom host name: $CUSTOM_HOSTNAME"
     - name: Printint repository secret
       env:
         MY_API_KEY: ${{secrets.API_KEY}}
       run: |
         echo "API_KEY is $MY_API_KEY"
     - name: Call GitHub API
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
          curl -H "Authorization: Bearer $GH_TOKEN" \
             -H "Accept: application/vnd.github+json" \
             https://api.github.com/repos/${{ github.repository }}
     - name: Printing built-in variables
       run: |
        echo "github_ref: ${{github.ref}}"
        echo "github.ref_name ${{github.ref_name}}"
        echo "github.action ${{github.action}}"
        echo "github.sha ${{github.sha}}"
        echo "github.repository ${{github.repository}}"
        echo "github.workspace ${{github.workspace}}"
