name: Hello worl github actions

on: 
 workflow_dispatch: 
 push:
   branches:
     - main

jobs:
  first: 
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v6.0.2

     - name: Say hello
       run: echo "Hello from GitHub actions"

     - name: Show runner info
       run: |
         uname -a 
         pwd
         ls -la
  second:
   runs-on: ubuntu-latest
   steps:
     - name: Second job message
       run: echo 'This job runs after first job'
   
