name: Hello world github actions

on: 
 workflow_dispatch: 
 push:
   branches:
     - main

jobs:
  first: 
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v6.0.2

     - name: Say hello
       run: echo "Hello from GitHub actions"

     - name: Show runner info
       run: |
         uname -a 
         pwd
         ls -la
         
  second:
   runs-on: ubuntu-latest
   env:
     CUSTOM_HOSTNAME: "custom_host"
   steps:
     - name: Printing custom host name
       run: |
        echo "Custom host name: $CUSTOM_HOSTNAME"
     - name: Printing custom host name again
       env:
         CUSTOM_HOSTNAME: "custom_host2"
       run: |
        echo "Custom host name: $CUSTOM_HOSTNAME"
     - name: Printint repository secret
       env:
         MY_API_KEY: ${{secrets.API_KEY}}
       run: |
         echo "API_KEY is $MY_API_KEY"
   
